/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAppSuporteRouteImport } from './routes/_authenticated/app.suporte'
import { Route as AuthenticatedAppProgressoRouteImport } from './routes/_authenticated/app.progresso'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppMentoriaRouteImport } from './routes/_authenticated/app.mentoria'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppComunidadeRouteImport } from './routes/_authenticated/app.comunidade'
import { Route as AuthenticatedAdminPlanosRouteImport } from './routes/_authenticated/admin.planos'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin.pagamentos'
import { Route as AuthenticatedAdminModulosRouteImport } from './routes/_authenticated/admin.modulos'
import { Route as AuthenticatedAdminMentoriasRouteImport } from './routes/_authenticated/admin.mentorias'
import { Route as AuthenticatedAdminCursosRouteImport } from './routes/_authenticated/admin.cursos'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin.cupons'
import { Route as AuthenticatedAdminConteudoRouteImport } from './routes/_authenticated/admin.conteudo'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminAulasRouteImport } from './routes/_authenticated/admin.aulas'
import { Route as AuthenticatedAppCursoIndexRouteImport } from './routes/_authenticated/app.curso.index'
import { Route as AuthenticatedAppCursoSlugRouteImport } from './routes/_authenticated/app.curso.$slug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppSuporteRoute = AuthenticatedAppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProgressoRoute =
  AuthenticatedAppProgressoRouteImport.update({
    id: '/progresso',
    path: '/progresso',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMentoriaRoute =
  AuthenticatedAppMentoriaRouteImport.update({
    id: '/mentoria',
    path: '/mentoria',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComunidadeRoute =
  AuthenticatedAppComunidadeRouteImport.update({
    id: '/comunidade',
    path: '/comunidade',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminPlanosRoute =
  AuthenticatedAdminPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulosRoute =
  AuthenticatedAdminModulosRouteImport.update({
    id: '/modulos',
    path: '/modulos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMentoriasRoute =
  AuthenticatedAdminMentoriasRouteImport.update({
    id: '/mentorias',
    path: '/mentorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCursosRoute =
  AuthenticatedAdminCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConteudoRoute =
  AuthenticatedAdminConteudoRouteImport.update({
    id: '/conteudo',
    path: '/conteudo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAulasRoute = AuthenticatedAdminAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppCursoIndexRoute =
  AuthenticatedAppCursoIndexRouteImport.update({
    id: '/curso/',
    path: '/curso/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCursoSlugRoute =
  AuthenticatedAppCursoSlugRouteImport.update({
    id: '/curso/$slug',
    path: '/curso/$slug',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/aulas': typeof AuthenticatedAdminAulasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/mentorias': typeof AuthenticatedAdminMentoriasRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/app/comunidade': typeof AuthenticatedAppComunidadeRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/mentoria': typeof AuthenticatedAppMentoriaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/curso/$slug': typeof AuthenticatedAppCursoSlugRoute
  '/app/curso/': typeof AuthenticatedAppCursoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/aulas': typeof AuthenticatedAdminAulasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/mentorias': typeof AuthenticatedAdminMentoriasRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/app/comunidade': typeof AuthenticatedAppComunidadeRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/mentoria': typeof AuthenticatedAppMentoriaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/curso/$slug': typeof AuthenticatedAppCursoSlugRoute
  '/app/curso': typeof AuthenticatedAppCursoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin/aulas': typeof AuthenticatedAdminAulasRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/_authenticated/admin/mentorias': typeof AuthenticatedAdminMentoriasRoute
  '/_authenticated/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/_authenticated/app/comunidade': typeof AuthenticatedAppComunidadeRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/mentoria': typeof AuthenticatedAppMentoriaRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/progresso': typeof AuthenticatedAppProgressoRoute
  '/_authenticated/app/suporte': typeof AuthenticatedAppSuporteRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/curso/$slug': typeof AuthenticatedAppCursoSlugRoute
  '/_authenticated/app/curso/': typeof AuthenticatedAppCursoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/app'
    | '/admin/aulas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/cupons'
    | '/admin/cursos'
    | '/admin/mentorias'
    | '/admin/modulos'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/app/comunidade'
    | '/app/configuracoes'
    | '/app/mentoria'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
    | '/app/curso/$slug'
    | '/app/curso/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin/aulas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/cupons'
    | '/admin/cursos'
    | '/admin/mentorias'
    | '/admin/modulos'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/app/comunidade'
    | '/app/configuracoes'
    | '/app/mentoria'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/suporte'
    | '/admin'
    | '/app'
    | '/app/curso/$slug'
    | '/app/curso'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/aulas'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/conteudo'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/cursos'
    | '/_authenticated/admin/mentorias'
    | '/_authenticated/admin/modulos'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/admin/planos'
    | '/_authenticated/app/comunidade'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/mentoria'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/progresso'
    | '/_authenticated/app/suporte'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/app/curso/$slug'
    | '/_authenticated/app/curso/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/suporte': {
      id: '/_authenticated/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AuthenticatedAppSuporteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/progresso': {
      id: '/_authenticated/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AuthenticatedAppProgressoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mentoria': {
      id: '/_authenticated/app/mentoria'
      path: '/mentoria'
      fullPath: '/app/mentoria'
      preLoaderRoute: typeof AuthenticatedAppMentoriaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comunidade': {
      id: '/_authenticated/app/comunidade'
      path: '/comunidade'
      fullPath: '/app/comunidade'
      preLoaderRoute: typeof AuthenticatedAppComunidadeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/planos': {
      id: '/_authenticated/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AuthenticatedAdminPlanosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modulos': {
      id: '/_authenticated/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AuthenticatedAdminModulosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mentorias': {
      id: '/_authenticated/admin/mentorias'
      path: '/mentorias'
      fullPath: '/admin/mentorias'
      preLoaderRoute: typeof AuthenticatedAdminMentoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cursos': {
      id: '/_authenticated/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AuthenticatedAdminCursosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/conteudo': {
      id: '/_authenticated/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AuthenticatedAdminConteudoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aulas': {
      id: '/_authenticated/admin/aulas'
      path: '/aulas'
      fullPath: '/admin/aulas'
      preLoaderRoute: typeof AuthenticatedAdminAulasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/curso/': {
      id: '/_authenticated/app/curso/'
      path: '/curso'
      fullPath: '/app/curso/'
      preLoaderRoute: typeof AuthenticatedAppCursoIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/curso/$slug': {
      id: '/_authenticated/app/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/app/curso/$slug'
      preLoaderRoute: typeof AuthenticatedAppCursoSlugRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAulasRoute: typeof AuthenticatedAdminAulasRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminConteudoRoute: typeof AuthenticatedAdminConteudoRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminCursosRoute: typeof AuthenticatedAdminCursosRoute
  AuthenticatedAdminMentoriasRoute: typeof AuthenticatedAdminMentoriasRoute
  AuthenticatedAdminModulosRoute: typeof AuthenticatedAdminModulosRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminPlanosRoute: typeof AuthenticatedAdminPlanosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAulasRoute: AuthenticatedAdminAulasRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminConteudoRoute: AuthenticatedAdminConteudoRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminCursosRoute: AuthenticatedAdminCursosRoute,
  AuthenticatedAdminMentoriasRoute: AuthenticatedAdminMentoriasRoute,
  AuthenticatedAdminModulosRoute: AuthenticatedAdminModulosRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedAdminPlanosRoute: AuthenticatedAdminPlanosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppComunidadeRoute: typeof AuthenticatedAppComunidadeRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppMentoriaRoute: typeof AuthenticatedAppMentoriaRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppProgressoRoute: typeof AuthenticatedAppProgressoRoute
  AuthenticatedAppSuporteRoute: typeof AuthenticatedAppSuporteRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCursoSlugRoute: typeof AuthenticatedAppCursoSlugRoute
  AuthenticatedAppCursoIndexRoute: typeof AuthenticatedAppCursoIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppComunidadeRoute: AuthenticatedAppComunidadeRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppMentoriaRoute: AuthenticatedAppMentoriaRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppProgressoRoute: AuthenticatedAppProgressoRoute,
  AuthenticatedAppSuporteRoute: AuthenticatedAppSuporteRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCursoSlugRoute: AuthenticatedAppCursoSlugRoute,
  AuthenticatedAppCursoIndexRoute: AuthenticatedAppCursoIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
