revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.has_role(uuid, public.app_role) from public, anon;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.has_role(uuid, public.app_role) to authenticated;
grant execute on function public.is_admin() to authenticated;
revoke all on function public.current_plan(uuid) from public, anon;
revoke all on function public.has_plan_access(uuid, public.plan_tier) from public, anon;
grant execute on function public.current_plan(uuid) to authenticated;
grant execute on function public.has_plan_access(uuid, public.plan_tier) to authenticated;
revoke all on function public.touch_updated_at() from public, anon, authenticated;